import {describe, expect, it} from 'vitest';
import {newProgress} from '../src/domain.js';
import {reduceProgress} from '../src/orchestration/progress-reducer.js';
import {renderStatus} from '../src/formatting/status.js';

const request = {id: 'r', conversationId: 'c', sourceMessageId: 'm', prompt: 'x', state: 'running' as const, acceptedAt: 0, startedAt: 0};

describe('progress', () => {
  it('keys interleaved same-name tools by call id and supports terminal states', () => {let progress = newProgress(); progress = reduceProgress(progress, {type: 'tool_queued', toolCallId: 'a', toolName: 'read_file', input: {file_path: 'a.ts'}}, 1); progress = reduceProgress(progress, {type: 'tool_running', toolCallId: 'b', toolName: 'read_file', input: {file_path: 'b.ts'}}, 2); progress = reduceProgress(progress, {type: 'tool_completed', toolCallId: 'a', toolName: 'read_file'}, 3); progress = reduceProgress(progress, {type: 'tool_denied', toolCallId: 'b', toolName: 'read_file'}, 4); progress = reduceProgress(progress, {type: 'subagent_start', subagentId: 's', description: 'reviewing'}, 5); progress = reduceProgress(progress, {type: 'subagent_stop', subagentId: 's'}, 6); expect(progress.tools.a.state).toBe('completed'); expect(progress.tools.b.state).toBe('denied'); expect(progress.subagents.s.state).toBe('completed'); expect(renderStatus(request, progress, 7000)).toContain('failed/blocked');});
  it('never renders raw input JSON', () => {let progress = newProgress(); progress = reduceProgress(progress, {type: 'tool_running', toolCallId: 'a', toolName: 'unknown', input: {secret: 'token'}}, 1); expect(renderStatus(request, progress, 1)).not.toContain('token');});
  it('explains long model waits without exposing private reasoning', () => {let progress = newProgress(); progress = reduceProgress(progress, {type: 'turn_start', turnNumber: 3}, 1_000); progress = reduceProgress(progress, {type: 'model_request_start', model: 'claude-sonnet'}, 2_000); const status = renderStatus(request, progress, 302_000); expect(status).toContain('Waiting for claude-sonnet to respond'); expect(status).toContain('turn 3 · model claude-sonnet'); expect(status).toContain('300s ago'); expect(status).toContain('Still connected'); expect(status).not.toMatch(/thinking|reasoning/i);});
  it('shows response and retry lifecycle phases', () => {let progress = newProgress(); progress = reduceProgress(progress, {type: 'model_request_start', model: 'model-a'}, 1); progress = reduceProgress(progress, {type: 'text_delta'}, 2); expect(renderStatus(request, progress, 3)).toContain('Receiving the model response'); progress = reduceProgress(progress, {type: 'api_retry', attempt: 4, delayMs: 5000}, 4); const status = renderStatus(request, progress, 5); expect(status).toContain('Model request retry 4 in 5s'); expect(status).toContain('Waiting for model-a to respond');});
});
