import {createHash} from 'node:crypto';
import {join} from 'node:path';
import {ChannelType, Client, GatewayIntentBits, Partials, REST, Routes, SlashCommandBuilder, type Attachment, type ChatInputCommandInteraction, type Message, type SendableChannels, type ThreadChannel} from 'discord.js';
import type {AppState, Destination} from '../domain.js';
import type {AttachmentInfo, DownloadableAttachment} from '../attachments.js';
import {buildAttachmentPrompt, DOWNLOAD_TIMEOUT_MS, downloadAttachments} from '../attachments.js';
import {transcribeVoiceFile, hasWhisperPrereqs} from '../transcription/whisper.js';
import type {DiscordPort, StreamHandle} from '../ports.js';
import type {Config} from '../config.js';
import {isAuthorized} from '../config.js';
import type {RequestCoordinator} from '../orchestration/request-coordinator.js';
import {SAFE_MENTIONS} from '../formatting/markdown.js';
import {routeIncoming, stripOwnMention} from './router.js';
import {sessionSummary} from './commands.js';

/** Structured result of transcribing one voice attachment. */
interface VoiceTranscript {name: string; ok: boolean; transcript?: string; error?: string}

export class DiscordAdapter implements DiscordPort {
  readonly client: Client;
  private coordinator?: RequestCoordinator;
  private channelIds = new Set<string>();
  private starterLocks = new Map<string, Promise<ThreadChannel>>();
  constructor(private readonly config: Config, private readonly state: AppState) {this.client = new Client({intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent, GatewayIntentBits.DirectMessages], partials: [Partials.Channel, Partials.Message]});}
  bind(coordinator: RequestCoordinator): void {this.coordinator = coordinator; this.client.on('messageCreate', message => void this.onMessage(message).catch(error => this.reportMessageError(message, error))); this.client.on('interactionCreate', interaction => {if (interaction.isChatInputCommand()) void this.onCommand(interaction).catch(error => this.reportCommandError(interaction, error));});}
  async start(): Promise<void> {await this.client.login(this.config.botToken); await new Promise<void>(resolve => this.client.isReady() ? resolve() : this.client.once('clientReady', () => resolve())); for (const guild of this.client.guilds.cache.values()) {if (this.config.guildId && guild.id !== this.config.guildId) continue; for (const channel of guild.channels.cache.values()) if (channel.type === ChannelType.GuildText && channel.name === this.config.channelName) this.channelIds.add(channel.id);} await this.registerCommands();}
  async stop(): Promise<void> {this.client.destroy();}
  async send(destination: Destination, content: string, nonce: string): Promise<{messageId: string}> {const channel = await this.channel(destination.channelId); const message = await channel.send({content, nonce: stableNonce(nonce), enforceNonce: true, allowedMentions: SAFE_MENTIONS}); return {messageId: message.id};}
  async edit(destination: Destination, messageId: string, content: string): Promise<void> {const channel = await this.channel(destination.channelId); const message = await channel.messages.fetch(messageId); await message.edit({content, allowedMentions: SAFE_MENTIONS});}
  async streamSend(destination: Destination): Promise<StreamHandle> {
    const channel = await this.channel(destination.channelId);
    const message = await channel.send({content: '🔵 Working…', allowedMentions: SAFE_MENTIONS});
    return {
      messageId: message.id,
      edit: async (content: string) => { await message.edit({content, allowedMentions: SAFE_MENTIONS}); },
      delete: async () => { await message.delete(); }
    };
  }
  async typing(destination: Destination): Promise<void> {const channel = await this.channel(destination.channelId); await channel.sendTyping();}
  isPermanentError(error: unknown): boolean {return [10003,10008,50001,50013].includes(Number((error as {code?: unknown})?.code));}
  private async channel(id: string): Promise<SendableChannels> {const channel = await this.client.channels.fetch(id); if (!channel?.isSendable()) throw new Error(`Discord destination ${id} is unavailable`); return channel;}
  private async onMessage(message: Message): Promise<void> {if (!this.coordinator || message.author.bot || !this.client.user || !isAuthorized(message.author.id, memberRoles(message.member), this.config)) return; if (message.guildId && this.config.guildId && message.guildId !== this.config.guildId) return; if (message.partial) await message.fetch(); const persisted = Object.values(this.state.conversations).find(conversation => conversation.destination.kind === 'guild' && conversation.destination.starterMessageId === message.id); let destination = persisted?.destination; let conversationId = persisted?.id; if (!destination || !conversationId) {const route = routeIncoming({channelId: message.channelId, guildId: message.guildId, userId: message.author.id, isThread: message.channel.isThread(), parentChannelId: message.channel.isThread() ? message.channel.parentId : undefined, starterMessageId: message.id, mentionsBot: message.mentions.has(this.client.user)}, this.state.conversations, this.channelIds.has(message.channelId) ? message.channelId : undefined); destination = route.destination; conversationId = route.conversationId; if (route.createThread && message.guildId) {const thread = await this.threadFor(message); destination = {kind: 'guild', channelId: thread.id, threadId: thread.id, starterMessageId: message.id, guildId: message.guildId}; conversationId = `thread:${thread.id}`;}} if (!destination || !conversationId) return; const text = stripOwnMention(message.content, this.client.user.id); const rawAttachments = [...message.attachments.values()]; const {downloaded, fallback} = rawAttachments.length ? await this.processAttachments(rawAttachments, message.id) : {downloaded: [] as AttachmentInfo[], fallback: [] as string[]}; const voiceAtts = downloaded.filter(att => att.kind === 'voice'); let transcripts: VoiceTranscript[] = []; if (voiceAtts.length) {await this.typing(destination).catch(() => undefined); transcripts = await this.transcribeVoiceAttachments(downloaded); await this.echoVoiceTranscript(destination, message.id, transcripts).catch(() => undefined);} const attachmentPrompt = [downloaded.length ? buildAttachmentPrompt(downloaded) : '', fallback.length ? `Attachments (URLs only — download failed):\n${fallback.join('\n')}` : ''].filter(Boolean).join('\n\n'); const transcriptPrompt = transcripts.length ? `🗣 **Voice messages** (auto-transcribed):\n${transcripts.map(voicePromptLine).join('\n')}` : ''; const prompt = [text, transcriptPrompt, attachmentPrompt].filter(Boolean).join('\n\n'); if (!prompt) {await message.reply({content: 'Please include text or an attachment with your request.', allowedMentions: SAFE_MENTIONS}); return;} await this.coordinator.accept({conversationId, destination, sourceMessageId: message.id, prompt, title: message.guildId ? deriveName(text || rawAttachments[0]?.name || 'Attachment request') : 'DM', attachments: downloaded.length ? downloaded : undefined});}
  private async processAttachments(attachments: Attachment[], sourceMessageId: string): Promise<{downloaded: AttachmentInfo[]; fallback: string[]}> {const destDir = join(this.config.workingDir, '.discord-attachments', sourceMessageId); const downloadable: DownloadableAttachment[] = attachments.map(a => ({name: a.name, url: a.url, contentType: a.contentType ?? null, size: a.size})); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), DOWNLOAD_TIMEOUT_MS); try {return await downloadAttachments(downloadable, destDir, controller.signal);} finally {clearTimeout(timer);}}
  private async transcribeVoiceAttachments(downloaded: AttachmentInfo[]): Promise<VoiceTranscript[]> {const out: VoiceTranscript[] = []; const voices = downloaded.filter(att => att.kind === 'voice'); if (!voices.length || !hasWhisperPrereqs(this.config.whisper)) {for (const att of voices) out.push({name: att.name, ok: false, error: 'whisper not configured'}); return out;} for (const att of voices) {try {const result = await transcribeVoiceFile(att.localPath, this.config.whisper); if (result.success && result.transcript.trim()) {out.push({name: att.name, ok: true, transcript: result.transcript.trim()}); continue;} if (result.success) {out.push({name: att.name, ok: true, transcript: ''}); continue;} out.push({name: att.name, ok: false, error: result.error || 'unknown error'});} catch (error) {out.push({name: att.name, ok: false, error: error instanceof Error ? error.message : String(error)});}} return out;}
  private async echoVoiceTranscript(destination: Destination, sourceMessageId: string, transcripts: VoiceTranscript[]): Promise<void> {const lines = transcripts.map(voiceEchoLine); if (!lines.length) return; const content = `🎙️ **Voice received** — you said:\n${lines.map(line => `> ${line}`).join('\n')}`; const nonce = `voicereply:${sourceMessageId}`; await this.send(destination, content, nonce).catch(() => undefined);}
  private threadFor(message: Message): Promise<ThreadChannel> {const existing = this.starterLocks.get(message.id); if (existing) return existing; const operation = (async () => {if (message.hasThread && message.thread) return message.thread; const fetched = await this.client.channels.fetch(message.id).catch(() => null); if (fetched?.isThread()) return fetched; try {return await message.startThread({name: deriveName(stripOwnMention(message.content, this.client.user!.id)), autoArchiveDuration: 1440});} catch (error) {const code = String((error as {code?: unknown})?.code); if (code === 'MessageExistingThread' || code === '160004') {const exact = await this.client.channels.fetch(message.id); if (exact?.isThread()) return exact;} throw error;}})().finally(() => this.starterLocks.delete(message.id)); this.starterLocks.set(message.id, operation); return operation;}
  private async onCommand(interaction: ChatInputCommandInteraction): Promise<void> {if (!this.coordinator) return; await interaction.deferReply({ephemeral: true}); if (!isAuthorized(interaction.user.id, memberRoles(interaction.member), this.config) || (interaction.guildId && this.config.guildId && interaction.guildId !== this.config.guildId)) {await interaction.editReply({content: 'You are not authorized to use this bot.', allowedMentions: SAFE_MENTIONS}); return;} const conversation = Object.values(this.state.conversations).find(value => value.destination.channelId === interaction.channelId); const scoped = ['stop','reset','status','model'].includes(interaction.commandName); if (scoped && !conversation) {await interaction.editReply({content: 'No tracked conversation in this channel.', allowedMentions: SAFE_MENTIONS}); return;} let content: string; if (interaction.commandName === 'stop') content = await this.coordinator.stop(conversation!.id) ? 'Cancellation completed.' : 'No active request.'; else if (interaction.commandName === 'reset') content = `Session reset; ${await this.coordinator.reset(conversation!.id)} queued request(s) cleared.`; else if (interaction.commandName === 'status') content = sessionSummary(this.state, conversation!.id); else if (interaction.commandName === 'sessions') content = sessionSummary(this.state); else if (interaction.commandName === 'stats') content = `Requests: ${this.state.runtime.totalRequests} · completed: ${this.state.runtime.totalCompleted} · errors: ${this.state.runtime.totalErrors} · active: ${this.state.runtime.activeCount} · queued: ${this.state.runtime.queuedCount}`; else if (interaction.commandName === 'model') {conversation!.model = interaction.options.getString('name', true); content = `Model set to **${conversation!.model}**.`;} else content = 'Mention the bot in the configured channel, reply in a tracked thread, or send a DM. Use `/stop`, `/reset`, `/status`, `/sessions`, `/model`, or `/stats`.'; await interaction.editReply({content, allowedMentions: SAFE_MENTIONS});}
  private async reportMessageError(message: Message, error: unknown): Promise<void> {console.error('Discord message handling failed:', safeError(error)); await message.reply({content: 'I could not process that message. Please try again.', allowedMentions: SAFE_MENTIONS}).catch(() => undefined);}
  private async reportCommandError(interaction: ChatInputCommandInteraction, error: unknown): Promise<void> {console.error('Discord command handling failed:', safeError(error)); const payload = {content: 'The command could not be completed.', allowedMentions: SAFE_MENTIONS}; if (interaction.deferred || interaction.replied) await interaction.editReply(payload).catch(() => undefined); else await interaction.reply({...payload, ephemeral: true}).catch(() => undefined);}
  private async registerCommands(): Promise<void> {if (!this.client.user) return; const commands: Array<{toJSON(): unknown}> = [['help','Show usage'],['reset','Reset this conversation'],['status','Show conversation status'],['stop','Cancel the active request'],['sessions','List sessions'],['stats','Show runtime metrics']].map(([name,description]) => new SlashCommandBuilder().setName(name!).setDescription(description!)); commands.push(new SlashCommandBuilder().setName('model').setDescription('Set the model').addStringOption(option => option.setName('name').setDescription('Model name').setRequired(true))); const rest = new REST().setToken(this.config.botToken); const body = commands.map(command => command.toJSON()); await rest.put(this.config.guildId ? Routes.applicationGuildCommands(this.client.user.id, this.config.guildId) : Routes.applicationCommands(this.client.user.id), {body});}
}
function stableNonce(value: string): string {return createHash('sha256').update(value).digest('hex').slice(0,25);}
function deriveName(content: string): string {const value = content.replace(/\s+/g,' ').trim(); return value.length > 100 ? `${value.slice(0,97)}...` : value || 'New session';}
function safeError(error: unknown): string {return error instanceof Error ? error.message.slice(0,300) : String(error).slice(0,300);}
/** Escape control characters / prompt-injection risk in attachment names. */
function sanitize(value: string): string {return value.replace(/[\n\r\t\0]/g, ' ').slice(0, 200);}
/** Prompt-side line for a voice transcript (feeds the agent). */
function voicePromptLine(t: VoiceTranscript): string {if (t.ok && t.transcript) return `- ${sanitize(t.name)}: "${sanitize(t.transcript)}"`; if (t.ok) return `- ${sanitize(t.name)}: (voice note — returned no speech; likely silent or inaudible)`; return `- ${sanitize(t.name)}: audio could not be transcribed (${sanitize(t.error || 'unknown error')})`;}
/** User-facing echo line for the chat acknowledgment. */
function voiceEchoLine(t: VoiceTranscript): string {if (t.ok && t.transcript) return `"${sanitize(t.transcript)}"`; if (t.ok) return `(voice note — no speech detected)`; return `(couldn't transcribe: ${sanitize(t.error || 'unknown error')})`;}
// Extract a member's roles as {id,name} from either a cached GuildMember (Collection)
// or a raw API interaction member (roles is a plain array of role IDs).
function memberRoles(member: unknown): Array<{id: string; name: string}> {
  if (!member || typeof member !== 'object') return [];
  const roles = (member as {roles?: unknown}).roles;
  if (!roles) return [];
  const value = (roles as {cache?: unknown}).cache;
  if (value && typeof (value as {values?: unknown}).values === 'function') {
    return [...(value as {values(): Iterable<{id: string; name: string}>}).values()].map(role => ({id: role.id, name: role.name}));
  }
  if (Array.isArray(roles)) return roles.map(id => ({id: String(id), name: ''}));
  return [];
}
